Issue #CO-508 fix: Contribute & sourcing load
Sunbird-coKreat/creation-portal pull request #2229
Opened 2023-06-29 11:43 UTC by shubhambansaltarento

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions: Angular 8, Nodejs 12.16.1
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

https://project-sunbird.atlassian.net/browse/CO-508

2023-06-29 14:50 UTC, vinukumar-vs requested changes

2023-06-29 14:50 UTC, vinukumar-vs commented on src/app/client/src/app/modules/shared-feature/components/program-list/program-list.component.ts
>      this.issourcingOrgAdmin = this.userService.isSourcingOrgAdmin();
Why not you moving the code as well to the above subscription? Because only after userData verify the user & his role.

`this.userService.userData$.subscribe(data =>{
      this.checkIfUserIsContributor();
      this.issourcingOrgAdmin = this.userService.isSourcingOrgAdmin();
    })`

2023-06-29 14:50 UTC, vinukumar-vs commented on src/app/client/src/app/modules/shared-feature/components/program-list/program-list.component.ts
>      this.issourcingOrgAdmin = this.userService.isSourcingOrgAdmin();
I would suggest to move all the below code of this function into the subscribe only...

2023-06-29 14:50 UTC, vinukumar-vs commented on src/app/client/src/app/app.component.ts
> +    if (this.userService.loggedIn) {
Below If-else condition itself should not be part of this function.

in the userData.subscribe function only do all the check of if-else

2023-06-30 04:23 UTC, shubhambansaltarento commented on src/app/client/src/app/app.component.ts
> +    if (this.userService.loggedIn) {
here there no userdata subscribe being used now 
I have removed the subscribe and merge map

2023-06-30 07:07 UTC, vinukumar-vs approved these changes

2023-06-30 07:08 UTC, merged