Fb/csp lib intigration
Sunbird-coKreat/creation-portal pull request #2244
Opened 2023-08-09 10:37 UTC by shubhambansaltarento

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions: Angular 8, Nodejs 12.16.1
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-08-09 10:47 UTC, vinukumar-vs requested changes

2023-08-09 10:47 UTC, vinukumar-vs commented on src/app/client/package.json
> +    "@project-sunbird/sunbird-file-upload-library": "^1.0.1",
Remove the ^ for NPM package version.

2023-08-09 10:47 UTC, vinukumar-vs commented on src/app/client/src/app/modules/program/components/create-program/create-program.component.ts
> +        uploader.upload({url: signedURL, file: this.uploader.getFile(0), csp: this.helperService.cloudStorageProvider.toLocaleLowerCase()})
How are we handling the errors? If there is any error, then we should log some telemetry error events for failures right.

2023-08-30 06:48 UTC, vaivk369 commented on src/app/client/src/app/modules/sourcing/components/content-uploader/content-uploader.component.ts
>        this.uploadInprogress = true;
@shubhambansaltarento in this file azureUploadFileService is still there and that is why the build is failing.. 
Also,   if (this.videoFileFormat) {
      this.azureUploadFileService.abortUpload();
    }
    is there. Please check.
    cc: @vinukumar-vs

2024-07-04 05:00 UTC, closed without merging