Issue #CO-514 : CSP Angular library integration and collection, question-set editor changes
Sunbird-coKreat/creation-portal pull request #2245
Opened 2023-08-10 09:15 UTC by shubhambansaltarento

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions: Angular 8, Nodejs 12.16.1
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-08-10 09:30 UTC, vinukumar-vs reviewed
package.json file with portal version as 6.1.0 is must.

2023-08-10 09:30 UTC, vinukumar-vs commented on src/app/client/src/app/modules/sourcing/components/content-uploader/content-uploader.component.ts
> +        console.log("this is file", this.uploader.getFile(0))
Too many console logs, hope added only for testing. It will be deleted in later PR

2023-08-11 04:40 UTC, shubhambansaltarento commented on src/app/client/src/app/modules/sourcing/components/content-uploader/content-uploader.component.ts
> +        console.log("this is file", this.uploader.getFile(0))
yes vinu, ill remove the console.log changes

2023-08-11 05:18 UTC, vinukumar-vs requested changes

2023-08-11 05:18 UTC, vinukumar-vs commented on src/app/client/src/app/modules/program/components/create-program/create-program.component.ts
> +  // uploadToBlob(signedURL, file, config): Observable<any> {
Remove this code.

2023-08-11 05:18 UTC, vinukumar-vs commented on src/app/client/src/app/modules/program/components/create-program/create-program.component.ts
> +              console.log(error);
Error should be handled with the message properly similar to above error logic
```
  const errInfo = {
          errorMsg: 'Unable to get pre_signed_url and Content Creation Failed, Please Try Again',
          telemetryPageId: this.telemetryPageId, telemetryCdata : this.telemetryInteractCdata,
          env : this.activatedRoute.snapshot.data.telemetry.env, request: request};
        this.loading = false;
        this.isClosable = true;
        return throwError(this.sourcingService.apiErrorHandling(err, errInfo));
```

2023-08-11 05:18 UTC, vinukumar-vs commented on src/app/client/src/app/modules/sourcing/components/ckeditor-tool/ckeditor-tool.component.ts
> +              console.log(error);
Error message should be shown properly.

2023-08-11 05:18 UTC, vinukumar-vs commented on src/app/client/src/app/modules/sourcing/components/ckeditor-tool/ckeditor-tool.component.ts
> +  // uploadToBlob(signedURL, file, config): Observable<any> {
remove this commented code.

2023-08-11 05:18 UTC, vinukumar-vs commented on src/app/client/src/app/modules/sourcing/components/question-set-editor/question-set-editor.component.ts
> +          provider: provider
You have to remove the editor.config.json file as well by replace
"presigned_headers" with "provider"

2023-08-11 05:18 UTC, vinukumar-vs commented on src/app/client/src/app/modules/sourcing/components/question-set-editor/question-set-editor.component.ts
> +    const provider = this.helperService.cloudStorageProvider.toLowerCase();
Remove the method in HelperService.js
addCloudStorageProviderHeaders

2023-08-11 05:18 UTC, vinukumar-vs commented on src/app/client/src/app/modules/workspace/components/content-editors/collection-editor/collection-editor.component.ts
> +    const provider = this.helperService.cloudStorageProvider.toLowerCase();
This is not required.

2023-08-11 06:08 UTC, shubhambansaltarento commented on src/app/client/src/app/modules/program/components/create-program/create-program.component.ts
> +              console.log(error);
error log added

2023-08-11 06:08 UTC, shubhambansaltarento commented on src/app/client/src/app/modules/sourcing/components/ckeditor-tool/ckeditor-tool.component.ts
> +              console.log(error);
error msg added

2023-08-11 06:09 UTC, shubhambansaltarento commented on src/app/client/src/app/modules/sourcing/components/question-set-editor/question-set-editor.component.ts
> +          provider: provider
replaced the object

2023-08-11 06:10 UTC, shubhambansaltarento commented on src/app/client/src/app/modules/workspace/components/content-editors/collection-editor/collection-editor.component.ts
> +    const provider = this.helperService.cloudStorageProvider.toLowerCase();
we have to make changes here because we have removed the header function from service

2023-08-11 06:11 UTC, shubhambansaltarento commented on src/app/client/src/app/modules/sourcing/components/question-set-editor/question-set-editor.component.ts
> +    const provider = this.helperService.cloudStorageProvider.toLowerCase();
removed the method

2023-08-11 06:11 UTC, shubhambansaltarento commented on src/app/client/src/app/modules/program/components/create-program/create-program.component.ts
> +  // uploadToBlob(signedURL, file, config): Observable<any> {
removed the commented code

2023-08-11 09:54 UTC, vinukumar-vs approved these changes

2023-08-11 09:54 UTC, merged