Issue #CO-514: Fix->environmetal varaible and cloud index file chanegs
Sunbird-coKreat/creation-portal pull request #2247
Opened 2023-08-25 08:54 UTC by shubhambansaltarento

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions: Angular 8, Nodejs 12.16.1
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-08-25 13:07 UTC, vinukumar-vs requested changes

2023-08-28 09:30 UTC, shubhambansaltarento commented on src/app/helpers/environmentVariablesHelper.js
>    sunbird_gcloud_project_id: env.sunbird_gcloud_project_id || '',
removed

2023-08-28 09:31 UTC, shubhambansaltarento commented on src/app/helpers/environmentVariablesHelper.js
removed

2023-08-28 09:31 UTC, shubhambansaltarento commented on src/app/helpers/environmentVariablesHelper.js
> -  sunbird_cloud_storage_container: env.sunbird_cloud_storage_container || '',
cloud_storage_provider is not new one this is only configured in CSP keys

2023-08-30 04:57 UTC, vinukumar-vs approved these changes

2023-08-30 04:58 UTC, merged