co-597 fix: diksha labelling
Sunbird-coKreat/creation-portal pull request #2257
Opened 2023-09-14 03:35 UTC by vaivk369

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions: Angular 8, Nodejs 12.16.1
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-21 08:43 UTC, vinukumar-vs requested changes

2023-09-21 08:43 UTC, vinukumar-vs commented on src/app/resourcebundles/data/consumption/en.properties
> +frmelmnts.btn.viewContentOnConsumption=View this content on DIKSHA
The value is not changed. Only key is changed.
"View this content on DIKSHA"

2023-09-21 08:43 UTC, vinukumar-vs commented on src/app/resourcebundles/data/consumption/en.properties
> +frmelmnts.btn.viewContentOnConsumptionError=ERROR: Content is not available on DIKSHA
Value also have "DIKSHA" keyword.

2023-09-21 08:43 UTC, vinukumar-vs commented on src/app/resourcebundles/data/consumption/en.properties
> +frmelmnts.lbl.publishedforconsumption=Published on DIKSHA
Value also have DIKSHA keyword

2023-09-22 10:17 UTC, vaivk369 commented on src/app/client/src/app/modules/shared/services/config/app.config.json
> -    "downloadDikshaApp": "https://play.google.com/store/apps/details?id=in.gov.diksha.app"
was not used anywhere and that is why removed

2023-09-23 04:16 UTC, vinukumar-vs requested changes

2023-09-23 04:16 UTC, vinukumar-vs commented on src/app/routes/googleSignInRoutes.js
> +    return 'Your account could not be created on Sunbird due to your Google Security settings';
This should be instance name. It should not hardcode as Sunbird. 
If so for all adopters has to do code change to show their instance name.

2024-07-16 11:45 UTC, closed without merging