Issue #CO-695: Reports headers and program headers dynamic
Sunbird-coKreat/creation-portal pull request #2277
Opened 2023-11-22 04:48 UTC by shubhambansaltarento

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions: Angular 8, Nodejs 12.16.1
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-11-22 11:48 UTC, vinukumar-vs requested changes

2023-11-22 11:48 UTC, vinukumar-vs commented on src/app/client/package.json
> +    "util": "^0.12.5",
Remove all the "^" for NPM packages. This will cause build failures later if there are any breaking changes in the patch versions.

2023-11-22 11:48 UTC, vinukumar-vs commented on src/app/client/src/app/app.component.ts
> +    console.log('data', data);
Remove this console log

2023-11-22 11:48 UTC, vinukumar-vs commented on src/app/client/src/app/app.component.ts
> +        this.cslFrameworkService.setDefaultFWforCsl('', this.userService.hashTagId);
This is happening only for logged in user. What about anonymous user?

2023-11-22 12:04 UTC, vinukumar-vs requested changes
Lot of console logs are present. Remove the console logs

2023-11-22 12:04 UTC, vinukumar-vs commented on src/app/client/src/app/modules/public/services/csl-framework/csl-framework.service.spec.ts
> +describe('CslFrameworkService', () => {
No proper unit-tests.

2023-11-22 12:04 UTC, vinukumar-vs commented on src/app/client/src/app/modules/shared-feature/components/project-filter/project-filter.component.ts
> +  public framework: any ={
WHy it is hardcoded here?

2023-11-22 15:56 UTC, vinukumar-vs requested changes

2023-11-22 15:56 UTC, vinukumar-vs commented on src/app/client/src/app/modules/shared-feature/components/program-list/program-list.component.ts
> +      filters = { ...filters,...appliedfilters};
What is the reason for taking out the 
`this.addFiltersInRequestBody(appliedfilters)`

2023-11-22 15:56 UTC, vinukumar-vs commented on src/app/client/src/app/modules/shared-feature/components/textbook-list/textbook-list.component.ts
> +    description: "Sunbird TPD framework",
Again harcoded JSON object

2023-11-22 15:56 UTC, vinukumar-vs commented on src/app/client/src/app/modules/shared/services/config/app.config.json
> +    "channel":"0138934136407244800",
These default values are not right.. How it will be same for new adopter.

2023-11-22 15:56 UTC, vinukumar-vs commented on src/app/client/src/app/modules/sourcing/components/chapter-list/chapter-list.component.ts
> +    (<HTMLInputElement>document.getElementById('portalCloudStorageUrl')).value : "https://dockstorage.blob.core.windows.net/content-service/";
Remove the fallback value

2023-12-04 10:07 UTC, shubhambansaltarento commented on src/app/client/src/app/modules/program/components/program-nominations/program-nominations.component.ts
> +      this.programDetails.config.categories = this.cslFrameworkService?.getFrameworkCategoriesObject();
we need data from CSL on program detail screen where the component is re-loaded

2023-12-04 10:08 UTC, shubhambansaltarento commented on src/app/client/src/app/modules/public/services/csl-framework/csl-framework.service.spec.ts
> +describe('CslFrameworkService', () => {
ill add it later

2023-12-04 10:55 UTC, shubhambansaltarento commented on src/app/client/src/app/modules/shared/services/config/app.config.json
> +    "channel":"0138934136407244800",
We need to provide it, its in the CSL design

2023-12-13 12:14 UTC, vinukumar-vs approved these changes

2023-12-13 12:19 UTC, merged