Issue #IQ-653 fix: Updated QuML Player, Resouce Library and Questionset Editor Version
Sunbird-coKreat/creation-portal pull request #2299
Opened 2023-12-29 12:07 UTC by rajnishdargan

2024-01-05 05:02 UTC, vinukumar-vs requested changes

2024-01-05 05:02 UTC, vinukumar-vs commented on src/app/client/src/app/modules/sourcing/components/chapter-list/chapter-list.component.ts
> +              this.parseBloomLevel(data.complexityLevel);
Why are you making this change in all the places, I told you to use existing `bloomsLevel` itself rather than writing the code for `complexityLevel`.

When you get the API response for chapter-list, there itself you assign `complexityLevel` to `bloomsLevel`. 

So you no need to do any other code change.

2024-01-05 07:29 UTC, rajnishdargan commented on src/app/client/src/app/modules/sourcing/components/chapter-list/chapter-list.component.ts
> +              this.parseBloomLevel(data.complexityLevel);
Modifying after getting API response will need a iteration to all the children of hierarchy data that could take more execution time so I have added new condition in the same method where if `objectType` is `Question/Questionset` (so it would not affect other collection types) and if it has `complexityLevel` then only assign `complexityLevel` to `bloomsLevel`

Removed above condition from this place. Please review the latest code.

2024-01-08 07:37 UTC, vinukumar-vs requested changes

2024-01-08 07:37 UTC, vinukumar-vs commented on src/app/client/src/app/modules/sourcing/components/chapter-list/chapter-list.component.ts
> +        delete data.complexityLevel;
Why do you want to delete the "complexityLevel". This is the new property should continue to be present in the data & code reference.

2024-01-08 07:37 UTC, vinukumar-vs commented on src/app/client/src/app/modules/sourcing/components/chapter-list/chapter-list.component.ts
> +      bloomsLevel: node.bloomsLevel,
I would suggest the should be like below
`bloomsLevel: node.complexityLevel || node.bloomsLevel`

So that `bloomsLevel` will be updated with `complexityLevel` data

2024-01-08 08:22 UTC, rajnishdargan commented on src/app/client/src/app/modules/sourcing/components/chapter-list/chapter-list.component.ts
> +      bloomsLevel: node.bloomsLevel,
done.

2024-01-08 08:24 UTC, merged