Issue #CO-957: user nomination issue
Sunbird-coKreat/creation-portal pull request #2340
Opened 2024-05-20 07:38 UTC by shubhambansaltarento

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions: Angular 8, Nodejs 12.16.1
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-05-20 07:45 UTC, vinukumar-vs requested changes

2024-05-20 07:45 UTC, vinukumar-vs commented on src/app/client/src/app/modules/contribute/components/program/program.component.ts
> +      this.frameworkCategories.forEach((cat) => this.frameworkCategoriesForNomination.push(cat.code));
Is the frameworkCategories are different for nomations? 
Why do you need this.

2024-05-20 07:45 UTC, vinukumar-vs commented on src/app/client/src/app/modules/contribute/components/program/program.component.ts
> +        frameworkCategories: this.frameworkCategoriesForNomination
Why can't you write the above function within this method and use function level variable instead of Private level variable(frameworkCategoriesForNomination)?

You already have `this.frameworkCategories` available at private level

2024-05-20 08:10 UTC, shubhambansaltarento commented on src/app/client/src/app/modules/contribute/components/program/program.component.ts
> +      this.frameworkCategories.forEach((cat) => this.frameworkCategoriesForNomination.push(cat.code));
removed the variable

2024-05-21 03:53 UTC, vinukumar-vs approved these changes
Super..

2024-05-21 03:54 UTC, merged